---
# Source: grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-6.57.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/version: "9.5.2"
    app.kubernetes.io/managed-by: Helm
  name: loki-grafana-clusterrole
rules: []
