apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - clusterrole.yaml
  - service.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - pvc.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - serviceaccount.yaml