---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.57.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/version: "9.5.2"
    app.kubernetes.io/managed-by: Helm
rules: []
