---
# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.57.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/version: "9.5.2"
    app.kubernetes.io/managed-by: Helm
  name: loki-grafana
  namespace: monitoring
